version: '3'

services:
  laravel.test:
    build:
      context: ./docker/laravel
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: laravel-sail
    container_name: laravel-app
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - mysql

  mysql:
    image: 'mysql:8.0'
    container_name: mysql-db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'sail-mysql:/var/lib/mysql'
    networks:
      - sail

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  sail-mysql:
    driver: local
